### ISSUE TITLE
Donor potal login button dosn't change after logging in

### ISSUE THREAD

**Issue by manuranga** [LSFLK/MedicinesforLK#438] opened 2022-08-28 12:46 UTC
Logging button remain "Login" but I can pledge.

**Comment by nipunsampath** [comment] 2022-08-29 08:23
@manuranga was this the dev environment? I couldn't reproduce this locally.

**Comment by manuranga** [comment] 2022-08-29 08:26
Yes, but it's there in prod as well. Could be a firefox issue.

**Comment by nipunsampath** [comment] 2022-08-29 09:08
Ack, I'll try with firefox.

**Comment by nipunsampath** [comment] 2022-09-02 12:29
- The login issue on the prod was resolved when the latest changes were deployed. 

- The login was failing on [donor-portal-rouge.vercel.app](https://donor-portal-rouge.vercel.app/) because the environment variable `REACT_APP_CLIENT_ID` was not visible to the preview environment on Vercel. That's why it was not locally reproducible.

I think we can close the issue. Please reopen this if you reencounter this.

**Closed by nipunsampath** 2022-09-02 12:29 UTC
Labels: bug, Donor Portal
